import React, { useEffect, useState } from "react";
import axios from "axios";
import {
  FaHistory,
  FaSearch,
  FaRobot,
  FaUserInjured,
  FaCheckCircle,
  FaClock,
} from "react-icons/fa";

import "./PredictionHistoryCopy.css";

const PredictionHistoryCopy = () => {

  const [predictions, setPredictions] = useState([]);
  const [filteredPredictions, setFilteredPredictions] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {

    loadPredictions();

  }, []);

  const loadPredictions = async () => {

    try {

      const { data } = await axios.get(
        "https://hospital-backend-28d9.onrender.com/api/v1/prediction/all"
      );

      setPredictions(data.predictions);
      setFilteredPredictions(data.predictions);

    } catch (error) {

      console.log(error);

    }

  };

  useEffect(() => {

    const filtered = predictions.filter((item) =>
      item.patientName
        ?.toLowerCase()
        .includes(search.toLowerCase())
    );

    setFilteredPredictions(filtered);

  }, [search, predictions]);

  return (

    <div className="prediction-history-page">

      <div className="prediction-header">

        <div>

          <h1>

            <FaHistory />

            AI Prediction Records

          </h1>

          <p>

            View all AI disease prediction reports generated by the hospital system.

          </p>

        </div>

      </div>

      <div className="prediction-summary">

        <div className="summary-card">

          <FaRobot className="summary-icon" />

          <div>

            <h2>{predictions.length}</h2>

            <p>Total Predictions</p>

          </div>

        </div>

        <div className="summary-card">

          <FaCheckCircle className="summary-icon success" />

          <div>

            <h2>

              {
                predictions.filter(
                  (item) => item.status === "Completed"
                ).length
              }

            </h2>

            <p>Completed</p>

          </div>

        </div>

        <div className="summary-card">

          <FaClock className="summary-icon pending" />

          <div>

            <h2>

              {
                predictions.filter(
                  (item) => item.status === "Pending"
                ).length
              }

            </h2>

            <p>Pending</p>

          </div>

        </div>

        <div className="summary-card">

          <FaUserInjured className="summary-icon" />

          <div>

            <h2>{filteredPredictions.length}</h2>

            <p>Displayed</p>

          </div>

        </div>

      </div>

      <div className="search-section">

        <FaSearch />

        <input
          type="text"
          placeholder="Search Patient Name..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

      </div>

      <div className="table-card">

        <table>

          <thead>

            <tr>

              <th>Patient</th>

              <th>Disease</th>

              <th>Prediction</th>

              <th>Confidence</th>

              <th>Status</th>

              <th>Date</th>

            </tr>

          </thead>

          <tbody>

            {

              filteredPredictions.length > 0 ? (

                filteredPredictions.map((item) => (

                  <tr key={item._id}>

                    <td>{item.patientName}</td>

                    <td>{item.diseaseType}</td>

                    <td>{item.result}</td>

                    <td>

                      <div className="confidence-bar">

                        <div
                          className="confidence-fill"
                          style={{
                            width: `${item.confidence}%`,
                          }}
                        ></div>

                        <span>

                          {item.confidence}%

                        </span>

                      </div>

                    </td>

                    <td>

                      <span
                        className={
                          item.status === "Completed"
                            ? "status completed"
                            : "status pending"
                        }
                      >

                        {item.status}

                      </span>

                    </td>

                    <td>

                      {new Date(item.createdAt).toLocaleString()}

                    </td>

                  </tr>

                ))

              ) : (

                <tr>

                  <td colSpan="6">

                    No Prediction Records Found

                  </td>

                </tr>

              )

            }

          </tbody>

        </table>

      </div>

    </div>

  );

};

export default PredictionHistoryCopy;
