import React from "react";
import jsPDF from "jspdf";

const DownloadReportButton = ({
  patientName = "Unknown Patient",
  disease = "N/A",
  confidence = "0",
  recommendation = "No recommendation available.",
}) => {

  const downloadReport = () => {

    const pdf = new jsPDF("p", "mm", "a4");

    const today = new Date();

    // Header
    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, 210, 30, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("ShivShakti Hospital", 20, 16);

    pdf.setFontSize(11);
    pdf.text("AI Powered Hospital Management System", 20, 24);

    // Title
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(18);
    pdf.text("AI MEDICAL ANALYSIS REPORT", 20, 45);

    pdf.setDrawColor(180);
    pdf.line(20, 48, 190, 48);

    // Date
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");

    pdf.text(
      `Generated : ${today.toLocaleDateString()}  ${today.toLocaleTimeString()}`,
      20,
      58
    );

    // Patient Details
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.text("Patient Information", 20, 72);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    pdf.text(`Patient Name : ${patientName}`, 25, 84);
    pdf.text(`Hospital : ShivShakti Hospital`, 25, 94);

    // Prediction
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.text("AI Diagnosis", 20, 112);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    pdf.text(`Disease Detected : ${disease}`, 25, 124);

    pdf.text(`Confidence Score : ${confidence}%`, 25, 134);

    // Recommendation
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.text("Recommendation", 20, 152);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    pdf.text(
      recommendation,
      25,
      164,
      {
        maxWidth: 160,
      }
    );

    // Doctor Note
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.text("Doctor's Note", 20, 205);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    pdf.text(
      "This report is generated by the AI Disease Prediction System. Final diagnosis should always be confirmed by a qualified medical professional.",
      25,
      217,
      {
        maxWidth: 165,
      }
    );

    // Footer
    pdf.setDrawColor(180);
    pdf.line(20, 270, 190, 270);

    pdf.setFontSize(10);

    pdf.text(
      "© ShivShakti Hospital | AI Healthcare Management System",
      20,
      278
    );

    pdf.text(
      "This report is confidential.",
      20,
      284
    );

    pdf.save(
      `${patientName.replace(/\s+/g, "_")}_Medical_Report.pdf`
    );

  };

  return (

    <button
      className="downloadBtn"
      onClick={downloadReport}
    >
      📄 Download AI Medical Report
    </button>

  );

};

export default DownloadReportButton;
