import jsPDF from "jspdf";

const generatePDF = (
  patientName,
  disease,
  prediction,
  confidence,
  recommendation
) => {

  const doc = new jsPDF();

  const reportId =
    "AI-" + Math.floor(100000 + Math.random() * 900000);

  const currentDate = new Date();

  const riskLevel =
    confidence >= 90
      ? "High Risk"
      : confidence >= 70
      ? "Moderate Risk"
      : "Low Risk";

  // ===========================
  // Header
  // ===========================

  doc.setFillColor(25, 118, 210);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text("SHIVSHAKTI HOSPITAL", 105, 13, {
    align: "center",
  });

  doc.setFontSize(10);

  doc.text(
    "AI Powered Smart Healthcare System",
    105,
    21,
    {
      align: "center",
    }
  );

  // ===========================
  // Title
  // ===========================

  doc.setTextColor(0, 0, 0);

  doc.setFontSize(18);

  doc.text(
    "AI MEDICAL DIAGNOSIS REPORT",
    105,
    42,
    {
      align: "center",
    }
  );

  // ===========================
  // Patient Details Box
  // ===========================

  doc.roundedRect(15, 50, 180, 55, 3, 3);

  doc.setFontSize(12);

  doc.setFont("helvetica", "bold");

  doc.text("Patient Name :", 22, 63);
  doc.text("Report ID :", 22, 75);
  doc.text("Date :", 22, 87);
  doc.text("Time :", 120, 87);

  doc.setFont("helvetica", "normal");

  doc.text(patientName, 70, 63);

  doc.text(reportId, 70, 75);

  doc.text(
    currentDate.toLocaleDateString(),
    70,
    87
  );

  doc.text(
    currentDate.toLocaleTimeString(),
    145,
    87
  );

  // ===========================
  // Prediction Box
  // ===========================

  doc.roundedRect(15, 115, 180, 75, 3, 3);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);

  doc.text("AI Prediction Result", 22, 128);

  doc.setFontSize(12);

  doc.text("Disease :", 22, 143);
  doc.text("Prediction :", 22, 155);
  doc.text("Confidence :", 22, 167);
  doc.text("Risk Level :", 22, 179);

  doc.setFont("helvetica", "normal");

  doc.text(disease, 75, 143);

  doc.text(prediction, 75, 155);

  doc.text(`${confidence}%`, 75, 167);

  doc.text(riskLevel, 75, 179);

  // ===========================
  // Recommendation
  // ===========================

  doc.roundedRect(15, 200, 180, 60, 3, 3);

  doc.setFont("helvetica", "bold");

  doc.text("AI Recommendation", 22, 214);

  doc.setFont("helvetica", "normal");

  const recommendationText =
    doc.splitTextToSize(
      recommendation,
      165
    );

  doc.text(
    recommendationText,
    22,
    226
  );

  // ===========================
  // Footer
  // ===========================

  doc.line(20, 272, 190, 272);

  doc.setFont("helvetica", "bold");

  doc.text(
    "Doctor Signature",
    25,
    282
  );

  doc.text(
    "Hospital Seal",
    145,
    282
  );

  doc.setFontSize(10);

  doc.setFont("helvetica", "normal");

  doc.text(
    "Generated by ShivShakti AI Medical Diagnosis System",
    105,
    292,
    {
      align: "center",
    }
  );

  // ===========================
  // Save PDF
  // ===========================

  doc.save(
    `${patientName}_Medical_Report.pdf`
  );

};

export default generatePDF;