import jsPDF from "jspdf";

const generateReport = (
  patientName,
  disease,
  confidence,
  recommendation
) => {
  const doc = new jsPDF();

  const today = new Date();

  const reportId =
    "AI-" +
    Math.floor(100000 + Math.random() * 900000);

  const risk =
    confidence >= 90
      ? "High"
      : confidence >= 70
      ? "Medium"
      : "Low";

  // ===========================
  // HEADER
  // ===========================

  doc.setFillColor(25, 118, 210);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("SHIVSHAKTI HOSPITAL", 105, 15, {
    align: "center",
  });

  doc.setFontSize(11);
  doc.text(
    "AI Powered Smart Healthcare System",
    105,
    23,
    {
      align: "center",
    }
  );

  // ===========================
  // TITLE
  // ===========================

  doc.setTextColor(0, 0, 0);

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");

  doc.text(
    "AI MEDICAL DIAGNOSIS REPORT",
    105,
    45,
    {
      align: "center",
    }
  );

  // ===========================
  // PATIENT DETAILS
  // ===========================

  doc.setDrawColor(180);

  doc.roundedRect(15, 55, 180, 55, 3, 3);

  doc.setFontSize(12);

  doc.setFont("helvetica", "bold");
  doc.text("Patient Name :", 22, 68);

  doc.setFont("helvetica", "normal");
  doc.text(patientName, 70, 68);

  doc.setFont("helvetica", "bold");
  doc.text("Report ID :", 22, 80);

  doc.setFont("helvetica", "normal");
  doc.text(reportId, 70, 80);

  doc.setFont("helvetica", "bold");
  doc.text("Date :", 22, 92);

  doc.setFont("helvetica", "normal");
  doc.text(today.toLocaleDateString(), 70, 92);

  doc.setFont("helvetica", "bold");
  doc.text("Time :", 120, 92);

  doc.setFont("helvetica", "normal");
  doc.text(today.toLocaleTimeString(), 145, 92);

  // ===========================
  // AI RESULT
  // ===========================

  doc.roundedRect(15, 120, 180, 70, 3, 3);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);

  doc.text("AI Prediction Result", 22, 135);

  doc.setFontSize(12);

  doc.setFont("helvetica", "bold");
  doc.text("Disease :", 22, 150);

  doc.setFont("helvetica", "normal");
  doc.text(disease, 70, 150);

  doc.setFont("helvetica", "bold");
  doc.text("Confidence :", 22, 162);

  doc.setFont("helvetica", "normal");
  doc.text(`${confidence}%`, 70, 162);

  doc.setFont("helvetica", "bold");
  doc.text("Risk Level :", 22, 174);

  doc.setFont("helvetica", "normal");
  doc.text(risk, 70, 174);

  // ===========================
  // RECOMMENDATION
  // ===========================

  doc.roundedRect(15, 200, 180, 55, 3, 3);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);

  doc.text("AI Recommendation", 22, 214);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(
    recommendation,
    165
  );

  doc.text(lines, 22, 226);

  // ===========================
  // FOOTER
  // ===========================

  doc.line(20, 270, 190, 270);

  doc.setFont("helvetica", "bold");

  doc.text(
    "Doctor Signature",
    25,
    280
  );

  doc.text(
    "Hospital Seal",
    145,
    280
  );

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  doc.text(
    "Generated by ShivShakti AI Medical Diagnosis System",
    105,
    292,
    {
      align: "center",
    }
  );

  // ===========================
  // SAVE
  // ===========================

  doc.save(`${patientName}_Medical_Report.pdf`);
};

export default generateReport;